# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93d85c15ba9dfe1dc5dc879f4a4c9f58eb0ab4f9dd89eca28638ba672ed56c0329ef1ce5d65a9351d03df69b2543bf9da02fe4227ee6e3c8576fb884edeb94f5

test:
  secret_key_base: cd50281eed74a14746fd5d19c36dac767488c7c67543802392c96c615b6e7bc12bba91cc00a744aa97261b0cff6bb76f69d202404b4c00fc11a059ff357c39ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
